import { cleanup, render, screen, fireEvent, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { afterEach, expect, it, vi } from "vitest";
import { AnalysisControls } from "@/components/investigation/AnalysisControls";
import { NarrativeNotebook } from "@/components/investigation/NarrativeNotebook";
import type { NarrativeEntry } from "@/types";
const request = vi.hoisted(() => vi.fn());
vi.mock("@/api", () => ({ liveRequest: request }));
afterEach(() => {
  cleanup();
  request.mockReset();
});
const wrap = () => (
  <QueryClientProvider
    client={
      new QueryClient({
        defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
      })
    }
  >
    <AnalysisControls caseId="case" evidenceCount={4} />
  </QueryClientProvider>
);
it("requests explicitly, disables duplicates and reports honest fallback", async () => {
  let finish!: (value: unknown) => void;
  request.mockImplementation((path: string) =>
    path === "/analysis/status"
      ? Promise.resolve({ configured: false })
      : new Promise((resolve) => {
          finish = resolve;
        }),
  );
  render(wrap());
  await waitFor(() => expect(request).toHaveBeenCalledTimes(1));
  fireEvent.click(screen.getByRole("button", { name: "Generate AI Analysis" }));
  await waitFor(() =>
    expect(screen.getByRole("button", { name: "Generating analysis…" })).toBeDisabled(),
  );
  expect(request.mock.calls[1]).toEqual(["/investigations/case/report", { method: "POST" }]);
  finish({ generated_by: "deterministic", fallback_reason: "not_configured" });
  await waitFor(() =>
    expect(screen.getByText(/Azure OpenAI is not configured. Deterministic/)).toBeVisible(),
  );
});
it("shows request failures and permits retry", async () => {
  request.mockImplementation((path: string) =>
    path === "/analysis/status"
      ? Promise.resolve({ configured: true })
      : Promise.reject(new Error("unavailable")),
  );
  render(wrap());
  fireEvent.click(screen.getByRole("button", { name: "Generate AI Analysis" }));
  await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("unavailable"));
  expect(screen.getByRole("button", { name: "Generate AI Analysis" })).toBeEnabled();
});
it("renders provenance, alternatives and clickable evidence", () => {
  const onCite = vi.fn();
  const entry = {
    id: "r",
    caseId: "c",
    question: "Evidence",
    answer: "Uncertain interpretation",
    facts: [{ text: "READ", evidenceIds: ["evt-real"] }],
    inferences: [],
    limitations: [],
    nextSteps: [],
    generatedBy: "azure-openai",
    modelDeployment: "actual-deployment",
    alternativeExplanations: ["Legitimate reporting"],
    provenance: {
      provider: "azure-openai",
      provider_model: "actual-model",
      created_at: "2026-10-09T00:00:00Z",
      evidence_fingerprint: "fingerprint",
      prompt_version: "v",
      validation_status: "observed-tuples-verified",
      fallback_reason: null,
      request_correlation_id: "request",
      generation_ms: 1,
    },
  } as NarrativeEntry;
  render(<NarrativeNotebook entry={entry} onCite={onCite} />);
  expect(screen.getByText("Generated by Azure OpenAI")).toBeVisible();
  expect(screen.getByText("Legitimate reporting")).toBeVisible();
  fireEvent.click(screen.getByRole("button", { name: "Open cited evidence evt-real" }));
  expect(onCite).toHaveBeenCalledWith("evt-real");
  expect(screen.queryByText(/Illustrative synthetic demo copy/)).toBeNull();
});
