/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DetectionRouteImport } from './routes/detection'
import { Route as InvestigatorRouteImport } from './routes/investigator'
import { Route as MovementRouteImport } from './routes/movement'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ResponseRouteImport } from './routes/response'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations.index'
import { Route as InvestigationsCaseIdRouteImport } from './routes/investigations.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionRoute = DetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigatorRoute = InvestigatorRouteImport.update({
  id: '/investigator',
  path: '/investigator',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementRoute = MovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponseRoute = ResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsCaseIdRoute = InvestigationsCaseIdRouteImport.update({
  id: '/investigations/$caseId',
  path: '/investigations/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/detection': typeof DetectionRoute
  '/investigator': typeof InvestigatorRoute
  '/movement': typeof MovementRoute
  '/playground': typeof PlaygroundRoute
  '/response': typeof ResponseRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/investigations/$caseId': typeof InvestigationsCaseIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/detection': typeof DetectionRoute
  '/investigator': typeof InvestigatorRoute
  '/movement': typeof MovementRoute
  '/playground': typeof PlaygroundRoute
  '/response': typeof ResponseRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/investigations/$caseId': typeof InvestigationsCaseIdRoute
  '/agents': typeof AgentsIndexRoute
  '/investigations': typeof InvestigationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/detection': typeof DetectionRoute
  '/investigator': typeof InvestigatorRoute
  '/movement': typeof MovementRoute
  '/playground': typeof PlaygroundRoute
  '/response': typeof ResponseRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/investigations/$caseId': typeof InvestigationsCaseIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/detection'
    | '/investigator'
    | '/movement'
    | '/playground'
    | '/response'
    | '/agents/$agentId'
    | '/investigations/$caseId'
    | '/agents/'
    | '/investigations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/detection'
    | '/investigator'
    | '/movement'
    | '/playground'
    | '/response'
    | '/agents/$agentId'
    | '/investigations/$caseId'
    | '/agents'
    | '/investigations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/detection'
    | '/investigator'
    | '/movement'
    | '/playground'
    | '/response'
    | '/agents/$agentId'
    | '/investigations/$caseId'
    | '/agents/'
    | '/investigations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DetectionRoute: typeof DetectionRoute
  InvestigatorRoute: typeof InvestigatorRoute
  MovementRoute: typeof MovementRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ResponseRoute: typeof ResponseRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  InvestigationsCaseIdRoute: typeof InvestigationsCaseIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigator': {
      id: '/investigator'
      path: '/investigator'
      fullPath: '/investigator'
      preLoaderRoute: typeof InvestigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement': {
      id: '/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof MovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/response': {
      id: '/response'
      path: '/response'
      fullPath: '/response'
      preLoaderRoute: typeof ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$caseId': {
      id: '/investigations/$caseId'
      path: '/investigations/$caseId'
      fullPath: '/investigations/$caseId'
      preLoaderRoute: typeof InvestigationsCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DetectionRoute: DetectionRoute,
  InvestigatorRoute: InvestigatorRoute,
  MovementRoute: MovementRoute,
  PlaygroundRoute: PlaygroundRoute,
  ResponseRoute: ResponseRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  InvestigationsCaseIdRoute: InvestigationsCaseIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
